# Name of your site
name: Test Site

# Short description
description: Test Site

# Your name, as you want it to appear underneath each post and in the footer
author: Daniel Klco

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://klcodanr.github.com/test-site/

# Exclude system files
exclude: [.gitignore]